[package]
edition = "2024"
name = "resynth"
version = "0.6.0"
description = "A packet synthesis language"
authors = ["Gianni Tedesco <gianni@scaramanga.co.uk>"]
license = "MIT"
homepage = "https://github.com/rapid7/resynth"
repository = "https://github.com/rapid7/resynth"
readme = "README.md"
keywords = [
 "packets",
 "packet-synthesis",
 "traffic-generation",
 "networking",
 "pcap",
]
categories = [
 "command-line-utilities",
 "compilers",
 "network-programming",
]
include = [
 "src/**/*.rs",
 "Cargo.toml",
 "README.md",
 "LICENSE.txt",
 "examples/*.rsyn",
 "doc/grammar.bnf",
 "doc/parser.dot",
]

[profile.release]
lto = true
panic = "abort"
incremental = true
codegen-units = 8

[profile.bench]
lto = true

[workspace]

[dependencies]
pkt = { path = "pkt", version = "0.6.0" }
ezpkt = { path = "ezpkt", version = "0.6.0" }

lazy-regex = "3.6"
regex = "1.12.3"
concat-with = "0.2.9"

# For cli
termcolor = {version = "1.4", optional = true}
clap = {version = "4.6", optional = true, features = ["cargo", "derive"]}
bytemuck = { version = "1.25.0", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["display", "error", "from"] }
serde_json = "1.0.149"
base64 = "0.22.1"

[[bin]]
name = "resynth"
path = "src/cli.rs"
required-features = ["cli"]

[features]
default = [
  "cli",
]
cli = ["clap", "termcolor"]
