[package]
name = "resynth"
version = "0.1.0"
authors = ["Gianni Tedesco <gianni@scaramanga.co.uk>"]
edition = "2018"
license = "GPLv3"
homepage = "https://github.com/giannitedesci/resynth"
repository = "https://github.com/giannitedesci/resynth"
readme = "README.md"
keywords = [
 "packets",
 "traffic-generation",
 "networking",
 "pcap",
]
categories = [
 "command-line-utilities",
 "compilers",
 "network programming",
]

[profile.release]
lto = true
panic = "abort"
incremental = true
codegen-units = 8

[profile.bench]
lto = true

[dependencies]
regex = "1.5"
lazy_static = "1.4.0"
phf = { version = "0.9", features = ["macros"] }
clap = "3.0.0-beta.2"
