program := [ ( stmt | program stmt ) ]

stmt := ( import | assignment | expr ) ";"

import := "import" IDENTIFIER

assignment := "let" IDENTIFIER "=" expr

qname := IDENTIFIER
	| qname "::" IDENTIFIER

primary := literal | qname | call

call := expr args_list

arg := expr
	| ( IDENTIFIER ":" expr )

args := arg
	| arg "," args

args_list :=  "(" ")"
	| "(" args ")" ;

expr := primary
	| ( expr "/" primary )
	| ( expr "." IDENTIFIER )

literal := BOOL | INTEGER | STRING | IPV4 | v4socket

v4socket := IPV4 ":" INTEGER
