[package]
edition = "2018"
name = "pkt"
version = "0.6.0"
description = "A packet construction library"
authors = ["Gianni Tedesco <gianni@scaramanga.co.uk>"]
license = "MIT"
homepage = "https://github.com/rapid7/resynth"
repository = "https://github.com/rapid7/resynth"
readme = "README.md"
keywords = [
 "packets",
 "traffic-generation",
 "networking",
 "pcap",
]
categories = [
 "network-programming",
]
include = [
 "src/**/*.rs",
 "Cargo.toml",
 "README.md",
 "LICENSE.txt",
]

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
